# -*- coding: utf-8 -*-
"""LGM_TASK_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lt2v1UuE33vBwXCdjTmbu10ImDPSGQUq

# **LGM- TASK 05**

# **INTERMEDIATE LEVEL TASK**

## **1) Exploratory Data Analysis on Dataset - Terrorism**

**As a security/defense analyst, try to find out the hot zone of terrorism.**

## **IMPORTING LIBRARIES:**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

data = pd.read_csv('terrorism.csv',encoding="latin1")
df = pd.DataFrame(data)
print("Data is imported Successfully!")

df.describe()

df.info()

df.shape

df.isnull().count()

df.columns

df['affected']=df['nkill']+df['nwound']
df['affected'].value_counts()

df['country_txt'].value_counts()

print("Maximally targetted Country is:", df['natlty1_txt'].value_counts().index[0])

print("Least targetted Country is:", df['natlty1_txt'].value_counts().index[-1])

"""# **DATA VISUALIZATION**"""

print("Maximally prefered type of Attacks:", df['attacktype1_txt'].value_counts().index[0])

plt.subplots(figsize=(15,10))
sn.countplot('attacktype1_txt',data=df,palette='inferno',hue = df['targtype1_txt'])
plt.xticks(rotation=70)
plt.xlabel('Attack Type')
plt.title('Attacking Methods wiht Target as hue')
plt.show()

print("Year with most number of Attacks:", df['iyear'].value_counts().index[0])

plt.subplots(figsize=(15,8))
sn.countplot('iyear',data=df,palette='Set1',edgecolor=sn.color_palette('dark',7))
plt.xticks(rotation=90)
plt.xlabel('Years')
plt.title('Number Of Terrorist Attacks')
plt.show()
print("Maximum Attacks mostly happened during the year of ",df['iyear'].value_counts().index[0])

plt.subplots(figsize=(15,8))
sn.countplot('imonth',data=df,palette='YlOrBr',edgecolor=sn.color_palette('dark',7))
plt.xticks(rotation=90)
plt.xlabel('Months')
plt.title('Number Of Terrorist Attacks')
plt.show()
print("Maximum Attacks mostly happened during the month of ",df['imonth'].value_counts().index[0])

plt.subplots(figsize=(15,10))
sn.countplot('attacktype1_txt',data=df,palette='inferno')
plt.xticks(rotation=70)
plt.xlabel('Attack Type')
plt.title('Attacking Methods')
plt.show()

df1 = df.sort_values(by='affected',ascending=False)[:20]
df1

heat =df1.pivot_table(index='country_txt',columns='iyear',values='affected')
heat.fillna(0,inplace=True)
heat.head()

sn.heatmap(heat,cmap='summer')
plt.xlabel('Year')
plt.ylabel('Country')
plt.title('Heatmap for Attacked with respect to Country and Year')

df['targtype1_txt'].value_counts()

print("Maximally Targeted:", df['targtype1_txt'].value_counts().index[0])

plt.subplots(figsize=(20,5))
sn.countplot('targtype1_txt',data=df,palette='Set1')
plt.xticks(rotation=90)
plt.xlabel('Target Type')
plt.title('Targets by Terrorists')
plt.show()

df['country_txt'].value_counts().index[:20]

print("Maximally Targeted Country:", df['country_txt'].value_counts().index[0])

plt.subplots(figsize=(15,6))
sn.barplot(df['country_txt'].value_counts().index[:20],df['country_txt'].value_counts()[:20].values,palette='magma')
plt.title('Top Countries Affected')
plt.xlabel('Countries')
plt.ylabel('Count')
plt.xticks(rotation= 90)
plt.show()

plt.subplots(figsize=(20,5))
sn.countplot('targsubtype1_txt',data=df,palette='flare',order=df['targsubtype1_txt'].value_counts().index)
plt.xticks(rotation=90)
plt.xlabel('Sub Target Type')
plt.title('Sub Targets by Terrorists')
plt.show()

df['region_txt'].value_counts()

df['affected'].value_counts()

"""### **CITY WISE AFFECTED ACROSS ALL YEARS**"""

df3 = df[['city','affected']].groupby('city').sum().sort_values(by="affected",ascending=False).drop("Unknown").head(10)
df3.plot(kind="bar",color="Green",figsize=(20,6))
plt.title("People Affected in each City",fontsize=15)
plt.xlabel("City",fontsize=15)
plt.ylabel("Number of People Affected",fontsize=15)

"""### **BOX PLOT TO FIND REGION WISE ATTACKS IN A PERIOD OF YEARS**"""

plt.subplots(figsize=(20,10))
sn.boxplot(x='region_txt',y='iyear',data=df)
plt.ylabel('Year')
plt.title('Attacks in Particular Regions Year wise')
plt.xlabel('Regions')
plt.xticks(rotation=90)
plt.show()

"""### **BAR PLOT TO SHOW GANGS INVLOVED IN THE ATTACKS**"""

print('Most attacks are done by',df['gname'][df['gname']!='Unknown'].value_counts().index[:20])

sn.barplot(df['gname'].value_counts().drop('Unknown').index[:10],df['gname'].value_counts().drop('Unknown')[:10].values)
plt.xticks(rotation=90)

plt.show()

"""## **COUNTRY WISE DEATHS,WOUNDED AND TOTAL(AFFECTED) ON ATTACKS**"""

df3=df['country_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('country_txt')['nwound'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['red','pink'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Counntry-wise Attacks vs Wounded')
plt.xlabel('Country')
plt.ylabel('count')
plt.show()

df3=df['country_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('country_txt')['nkill'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['blue','yellow'])
fig=plt.gcf()
plt.title('Counntry-wise Attacks vs Killed')
fig.set_size_inches(18,6)
plt.xlabel('Country')
plt.ylabel('count')
plt.show()

df3=df['country_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('country_txt')['affected'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['green','brown'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Counntry-wise Attacks vs Affected')
plt.xlabel('Country')
plt.ylabel('count')
plt.show()

df3=df['region_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('region_txt')['nkill'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['red','pink'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Region-wise Attacks vs kiled')
plt.xlabel('Region')
plt.ylabel('count')
plt.show()

"""### **REGION WISE DEATHS,WOUNDED AND TOTAL(AFFECTED)**"""

df3=df['region_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('region_txt')['nwound'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['red','black'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Region-wise Attacks vs Wounded')
plt.xlabel('Region')
plt.ylabel('count')
plt.show()

df3=df['region_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('region_txt')['affected'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['cyan','brown'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Region-wise Attacks vs Affected')
plt.xlabel('Region')
plt.ylabel('count')
plt.show()

"""## **GANG WISE DEATHS,WOUNDED AND TOTAL(AFFECTED) BASED ON ATTACKS**"""

print('Most attacks are done by',df['gname'].value_counts().drop('Unknown').index[0])

df3=df['gname'].value_counts()[:15].drop('Unknown').to_frame()
df3.columns=['Attacks']
data=df.groupby('gname')['affected'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['cyan','violet','red','green'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Gang-wise Attacks vs Affected')
plt.xlabel('Gangs')
plt.ylabel('count')
plt.show()

df3=df['gname'].value_counts()[:15].drop('Unknown').to_frame()
df3.columns=['Attacks']
data=df.groupby('gname')['nwound'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['cyan','violet','red','green'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Gang-wise Attacks vs Wounded')
plt.xlabel('Gangs')
plt.ylabel('count')
plt.show()

df3=df['gname'].value_counts()[:15].drop('Unknown').to_frame()
df3.columns=['Attacks']
data=df.groupby('gname')['nkill'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['cyan','green'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Gang-wise Attacks vs Killed')
plt.xlabel('Gangs')
plt.ylabel('count')
plt.show()

"""### **TARGET WISE DEATHS,WOUNDED AND TOTAL(AFFECTED) BASED ON ATTACKS**"""

print('Most attacks are targeted on',df['targtype1_txt'].value_counts().index[0])

df3=df['targtype1_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('targtype1_txt')['nwound'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['cyan','red'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Target-wise Attacks vs Wounded')
plt.xlabel('Target')
plt.ylabel('count')
plt.show()

df3=df['targtype1_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('targtype1_txt')['nkill'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.7,color=['brown','lightgreen'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Target-wise Attacks vs Killed')
plt.xlabel('Targets')
plt.ylabel('count')
plt.show()

df3=df['targtype1_txt'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('targtype1_txt')['affected'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['black','pink'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Target-wise Attacks vs Affected')
plt.xlabel('Targets')
plt.ylabel('count')
plt.show()

df4 = df.groupby('iyear')['country_txt'].sum().to_frame()
df4

"""### **YEAR WISE ATTACKS VS AFFECTED COMPARISION**"""

df['iyear'].value_counts()[:15]

df3=df['iyear'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('iyear')['affected'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['purple','green'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Year-wise Attacks vs affected')
plt.xlabel('Years')
plt.ylabel('count')
plt.show()

df3=df['iyear'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('iyear')['nwound'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['yellow','violet'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Year-wise Attacks vs Wounded')
plt.xlabel('Years')
plt.ylabel('count')
plt.show()

df3=df['iyear'].value_counts()[:15].to_frame()
df3.columns=['Attacks']
data=df.groupby('iyear')['nkill'].sum().to_frame()
df3.merge(data,left_index=True,right_index=True,how='left').plot.bar(width=0.9,color=['red','cyan'])
fig=plt.gcf()
fig.set_size_inches(18,6)
plt.title('Year-wise Attacks vs Killed')
plt.xlabel('Years')
plt.ylabel('count')
plt.show()

"""### **CONCLUSION:**

I have done Data Analysis for each region,country,city,target,year on Attacks versus Wounded,Killed,TotalAffected(Wounded + Killed). I have plotted box plot on Year vs Region to get a clear picture of which part of timeline each region is most affected, which helps to get an idea of outliers Also plotted which Gang is responsible for most number of attacks, which gang caused more damage(more people affected). Plotted a barplot for attacktypes and which attacktype is mostly used and which caused more damage


"""